name: cxone-iac-scan

on: 
  workflow_dispatch:

env:
  IMAGE_NAME: $GITHUB_WORKFLOW:$GITHUB_RUN_ID

jobs:
  Build:

    runs-on: ubuntu-latest
    
    steps:

      - name: Check out Code
        uses: actions/checkout@v3

      - name: echoing the file name
        run: echo $GITHUB_WORKFLOW:$GITHUB_RUN_ID

      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: cxone-pearson
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        
